version: '3'
services:
  hb-back:
    build: .
    ports:
      - "8001:3000"
    volumes:
     - ./:/home/node/app:ro

  postgres:
    image: postgis/postgis:13-master
    restart: always
    container_name: helpbuttons_postgres
    volumes:
     - ../db/:/var/lib/mysql:rw
     - ./data/postgres/:/migrations/:ro
    environment:
     - POSTGRES_PASSWORD=jgda7s8tds78sagda
    ports:
     - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
