name: ci-test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: docker-compose up -d postgres
      - run: npm i
      - run: docker exec helpbuttons_postgres /migrations/run_all.sh reset
      - run: npm run build
      - run: node_modules/.bin/lb-nyc ./node_modules/.bin/mocha ./dist/__tests__/**/*.test.js
