name: ci-test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "copy env.ci to .env"
        run: |
          cp env.ci .env
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "eslint"
        run: |
         yarn
         yarn eslint
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "copy env.ci to .env"
        run: |
          cp env.ci .env
      - name: "setup node"
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: "start postgis"
        run: |
         docker-compose up -d db 
      - name: "run the tests"
        run: |
         yarn test

